// src/components/Chat/ChatInput.tsx
import React, { useState } from 'react';

interface ChatInputProps {
  onSendMessage: (text: string) => void;
  isLoading: boolean;
}

export const ChatInput: React.FC<ChatInputProps> = ({ isLoading, onSendMessage }) => {
  const [texto, setTexto] = useState('');

  // En React, manejar el envío mediante un Form es la mejor práctica
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault(); // Evita que la página se recargue
    if (texto.trim() !== '' && !isLoading) {
      onSendMessage(texto);
      setTexto('');
    }
  };

  return (
    <form 
      onSubmit={handleSubmit}
      className="flex gap-2 p-4 bg-white border-t border-[#D4A373]/20"
    >
      <input
        value={texto}
        onChange={(e) => setTexto(e.target.value)}
        type="text"
        disabled={isLoading}
        placeholder={isLoading ? 'RAÍCES está pensando...' : 'Escribe tu pregunta aquí...'}
        className="flex-1 px-4 py-3 rounded-full border border-[#D4A373] text-base outline-none focus:border-[#C65D3B] disabled:bg-[#F5F1E8] transition-all"
      />
      
      <button 
        type="submit"
        disabled={isLoading || !texto.trim()}
        className="px-6 rounded-full font-bold text-white transition-all bg-[#C65D3B] disabled:bg-[#6B5E4F] disabled:opacity-50 disabled:cursor-not-allowed active:scale-95"
      >
        {isLoading ? (
          <span className="animate-pulse">...</span>
        ) : (
          "Enviar"
        )}
      </button>
    </form>
  );
};

// src/components/Chat/ChatInput.vue
<template>
  <div class="chat-input-container">
    <input
      v-model="texto"
      type="text"
      :disabled="isLoading"
      :placeholder="isLoading ? 'RAÍCES está pensando...' : 'Escribe tu pregunta aquí...'"
      @keydown.enter="enviar"
    />
    <button 
      @click="enviar" 
      :disabled="isLoading || !texto.trim()"
      class="send-button"
    >
      <span v-if="!isLoading">Enviar</span>
      <span v-else>...</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const props = defineProps<{ isLoading: boolean }>();
const emit = defineEmits(['onSendMessage']);

const texto = ref('');

const enviar = () => {
  if (texto.value.trim() !== '' && !props.isLoading) {
    emit('onSendMessage', texto.value);
    texto.value = ''; // <--- Limpieza de texto igual que en tu lógica original
  }
};
</script>

<style scoped>
.chat-input-container {
  display: flex;
  gap: 10px;
  padding: 16px;
  background: white;
  border-top: 1px solid rgba(212, 163, 115, 0.2);
}

input {
  flex: 1;
  padding: 12px 18px;
  border-radius: 25px;
  border: 1px solid #D4A373;
  outline: none;
  font-size: 1rem;
}

input:disabled { background-color: #F5F1E8; }

.send-button {
  background-color: #C65D3B;
  color: white;
  border: none;
  border-radius: 20px;
  padding: 0 20px;
  font-weight: bold;
  cursor: pointer;
}

.send-button:disabled { background-color: #6B5E4F; opacity: 0.5; }
</style>
