// src/components/Chat/SourceBadge.tsx
import React from 'react';

// 1. DEFINIMOS LA INTERFAZ (Esto quita el error "Cannot find name")
interface SourceBadgeProps {
  source: string;
}

// 2. EL COMPONENTE (Ahora sí sabe qué es SourceBadgeProps)
export const SourceBadge: React.FC<SourceBadgeProps> = ({ source }) => {
  const sourceLower = source.toLowerCase();
  const isMacrocaso = sourceLower.includes('001') || 
                      sourceLower.includes('m10') || 
                      sourceLower.includes('macrocaso');

  return (
    <div className="flex items-center gap-2 mt-2 pt-2 border-t border-dashed border-[#D4A373]/20">
      <div className={`px-1.5 py-0.5 rounded text-[9px] font-extrabold uppercase tracking-wider text-white ${
        isMacrocaso ? 'bg-[#C65D3B]' : 'bg-[#588157]'
      }`}>
        {isMacrocaso ? 'JEP - Macrocaso 10' : 'Fuente Oficial JEP'}
      </div>
      <span className="text-[9px] text-[#6B5E4F] italic truncate max-w-[140px]">
        Doc: {source}
      </span>
    </div>
  );
};

// src/components/Chat/SourceBadge.vue
<template>
  <div class="source-container">
    <div :class="['badge', isMacrocaso ? 'badge-m10' : 'badge-gen']">
      {{ isMacrocaso ? 'JEP - Macrocaso 10' : 'Fuente Oficial JEP' }}
    </div>
    <span class="source-text">Doc: {{ source }}</span>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{ source: string }>();

const isMacrocaso = computed(() => {
  const s = props.source.toLowerCase();
  return s.includes('001') || s.includes('m10') || s.includes('macrocaso');
});
</script>

<style scoped>
.source-container {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 8px;
  padding-top: 6px;
  border-top: 1px dashed rgba(212, 163, 115, 0.2);
}

.badge {
  padding: 2px 6px;
  border-radius: 4px;
  font-size: 9px;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: white;
}

.badge-m10 { background-color: #C65D3B; }
.badge-gen { background-color: #588157; }

.source-text {
  font-size: 9px;
  color: #6B5E4F;
  font-style: italic;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 140px;
}
</style>
