// src/components/Layout/Header.tsx
import React, { useState } from 'react';
import { clearAllHistory } from '@/core/db/sqlite.service';

interface HeaderProps {
  onExport: () => void;
}

export const Header: React.FC<HeaderProps> = ({ onExport }) => {
  const [clickCount, setClickCount] = useState(0);
  const [lastClickTime, setLastClickTime] = useState(0);

  const handleLogoClick = async () => {
    const now = Date.now();
    
    // Lógica de Pánico: 3 clics en menos de 1 segundo
    if (now - lastClickTime > 1000) {
      setClickCount(1);
    } else {
      const newCount = clickCount + 1;
      setClickCount(newCount);
      
      if (newCount === 3) {
        console.warn('[RAÍCES] ¡ACTIVADO PROTOCOLO DE PÁNICO!');
        await clearAllHistory();
        alert("Información protegida. La aplicación se cerrará.");
        window.location.href = "https://www.google.com";
      }
    }
    setLastClickTime(now);
  };

  return (
    <header className="bg-[#C65D3B] text-white p-3 px-5 flex justify-between items-center select-none shadow-md">
      <div className="cursor-pointer" onClick={handleLogoClick}>
        <h1 className="m-0 text-xl font-bold tracking-tight">RAÍCES</h1>
      </div>
      
      <div className="flex gap-2">
        <button 
          onClick={onExport}
          className="bg-white/15 border-none rounded-full w-9 h-9 flex items-center justify-center hover:bg-white/25 active:scale-90 transition-all"
        >
          <span>📄</span>
        </button>
      </div>
    </header>
  );
};

// src/components/Layout/Header.vue
<template>
  <header class="app-header">
    <div class="brand" @click="handleLogoClick">
      <h1>RAÍCES</h1>
    </div>
    <div class="actions">
      <button @click="$emit('onExport')" class="btn-icon">
        <span>📄</span>
      </button>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { clearAllHistory } from '@/core/db/sqlite.service';

const emit = defineEmits(['onExport']);
const clickCount = ref(0);
const lastClickTime = ref(0);

const handleLogoClick = async () => {
  const now = Date.now();
  // Si pasa más de 1 segundo entre clics, reiniciamos el contador
  if (now - lastClickTime.value > 1000) {
    clickCount.value = 1;
  } else {
    clickCount.value++;
  }
  
  lastClickTime.value = now;

  if (clickCount.value === 3) {
    // ACCIÓN DE PÁNICO: Borrado rápido y cierre
    console.warn('[RAÍCES] ¡ACTIVADO PROTOCOLO DE PÁNICO!');
    await clearAllHistory();
    alert("Información protegida. La aplicación se cerrará.");
    // En Capacitor, esto cierra la app
    window.location.href = "https://www.google.com"; 
  }
};
</script>

<style scoped>
.app-header {
  background-color: #C65D3B;
  color: white;
  padding: 12px 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  user-select: none;
}
.brand h1 { margin: 0; font-size: 1.3rem; cursor: pointer; }
.btn-icon {
  background: rgba(255,255,255,0.15);
  border: none;
  border-radius: 50%;
  width: 36px;
  height: 36px;
  color: white;
}
</style>
